# Generated by Django 5.2 on 2025-04-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundscore', '0001_initial'),
    ]

    operations = [
    ]
