version: "3.13" 

services:
  web:
    build: .
    volumes:
      - .:/soundscore
      - ./media:/soundscore/media
      - ./db.sqlite3:/soundscore/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
