version: "3.13"

services:
  web:
    build: .
    volumes:
      - ./apps:/soundscore/apps
      - ./media:/soundscore/media
      - ./db.sqlite3:/soundscore/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

