# Generated by Django 5.2 on 2025-07-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrelationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrelationship',
            unique_together={('user_id', 'following')},
        ),
        migrations.AlterModelTable(
            name='userrelationship',
            table='soundscore_user_relationship',
        ),
    ]
